require('core/options')
require('core/keymaps')
require('packer_init')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
require('plugins/nvim-lspconfig')
require('plugins/nvim-cmp')
require('plugins/lsp-signature')
require('plugins/indent-blankline')
vim.cmd "colorscheme gruvbox"
